name: 📦 Archive Gradle reports
description: Archive Gradle reports ...

inputs:
  id:
    description: A unique identifier when using matrix strategy to avoid collisions

runs:
  using: composite
  steps:
    - name: Dump GitHub context
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      shell: bash
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Archive ...
      uses: actions/upload-artifact@v4
      with:
        name: ${{ format('gradle-report-dependency-verification ({0})', inputs.id != '' && (github.job + '-' + inputs.id) || github.job) }}
        path: 'build/reports/dependency-verification'
        if-no-files-found: ignore
    - name: Archive ...
      uses: actions/upload-artifact@v4
      with:
        name: ${{ format('gradle-report-dependency-configuration-cache ({0})', inputs.id != '' && (github.job + '-' + inputs.id) || github.job) }}
        path: 'build/reports/dependency-configuration-cache'
        if-no-files-found: ignore
    - name: Archive ...
      uses: actions/upload-artifact@v4
      with:
        name: ${{ format('gradle-report-problems ({0})', inputs.id != '' && (github.job + '-' + inputs.id) || github.job) }}
        path: 'build/reports/problems/problems-report.html'
        if-no-files-found: ignore
    - name: Archive ...
      uses: actions/upload-artifact@v4
      with:
        name: ${{ format('gradle-report-licensee ({0})', inputs.id != '' && (github.job + '-' + inputs.id) || github.job) }}
        path: '**/build/reports/licensee'
        if-no-files-found: ignore
