name: 📦 Archive Paparazzi reports
description: Archive Paparazzi reports, failures and deltas
runs:
  using: composite
  steps:
    - name: Archive HTML report
      if: ${{ hashFiles('**/build/reports/paparazzi/**/*.html') != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: paparazzi-html
        path: '**/build/reports/paparazzi'
    - name: Archive failures & deltas
      if: ${{ hashFiles('**/build/paparazzi/failures/*.png') != '' }}
      id: artifact-failures-and-deltas
      uses: actions/upload-artifact@v4
      with:
        name: paparazzi-failures
        path: '**/build/paparazzi/failures/*.png'
    - if: ${{ hashFiles('**/build/paparazzi/failures/*.png') != '' && github.event_name == 'pull_request' }}
      run: gh pr comment "$PR_NUMBER" --body "[📸 Paparazzi Golden Images]($ARTIFACT_URL)"
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        ARTIFACT_URL: ${{ steps.artifact-failures-and-deltas.outputs.artifact-url }}
      continue-on-error: true
