name: 🤖 Setup Bot
description: Setup Bot

inputs:
  app-id:
    description: GitHub App ID
    required: true
  override-git-user:
    description: When 'true', the global git user will be set to the bot identity.
    required: false
    default: 'true'

outputs:
  app-slug:
    description: GitHub App slug
    value: ${{ steps.app-token.outputs.app-slug }}
  token:
    description: GitHub App installation access token
    value: ${{ steps.app-token.outputs.token }}
  user-id:
    description: GitHub App user id
    value: ${{ steps.get-user-id.outputs.user-id }}

runs:
  using: composite
  steps:
    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ secrets.BOT_PRIVATE_KEY }}
    - id: get-user-id
      run: echo "user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - run: gh auth status
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - run: gh auth login
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - run: gh auth status
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - if: inputs.override-git-user == 'true'
      run: |
        git config --global --list
        git config --global user.name "${APP_SLUG}[bot]"
        git config --global user.email "${APP_USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
      shell: bash
      env:
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        APP_USER_ID: ${{ steps.get-user-id.outputs.user-id }}
    - run: gh auth status
      shell: bash
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
