name: 🤖 Setup Bot
description: Setup Bot

inputs:
  app-id:
    description: GitHub App ID
    required: true
  private-key:
    description: GitHub App private key
    required: true
  override-git-user:
    description: When 'true', the global git user will be set to the bot identity.
    required: false
    default: 'true'

outputs:
  app-slug:
    description: GitHub App slug
    value: ${{ steps.app-token.outputs.app-slug }}
  token:
    description: GitHub App installation access token
    value: ${{ steps.app-token.outputs.token }}
  user-id:
    description: GitHub App user id
    value: ${{ steps.get-user-id.outputs.user-id }}
  committer:
    description: Git committer
    value: ${{ format('{0} <{1}+{2}[bot]@users.noreply.github.com>', steps.app-token.outputs.app-slug, steps.get-user-id.outputs.user-id, steps.app-token.outputs.app-slug) }}

runs:
  using: composite
  steps:
    - uses: actions/create-github-app-token@v2
      id: app-token
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.private-key }}
    - id: get-user-id
      run: echo "user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      shell: bash
      env:
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - run: |
        gh auth status || true
        git config --list
      shell: bash
      continue-on-error: true
    - run: gh auth login --with-token <<< "${{ steps.app-token.outputs.token }}"
      shell: bash
    - run: |
        gh auth status || true
        git config --list
      shell: bash
      continue-on-error: true
    - run: |
        date > foo.txt
        git add foo.txt
        git commit -m "foo"
        git show
      shell: bash
      continue-on-error: true
    - run: gh auth setup-git
      shell: bash
    - run: |
        gh auth status || true
        git config --list
      shell: bash
      continue-on-error: true
    - run: |
        date > bar.txt
        git add bar.txt
        git commit -m "bar"
        git show
      shell: bash
      continue-on-error: true
    - if: inputs.override-git-user == 'true'
      run: |
        git config --list
        git config --global user.name "${APP_SLUG}[bot]"
        git config --global user.email "${APP_USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
      shell: bash
      env:
        APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
        APP_USER_ID: ${{ steps.get-user-id.outputs.user-id }}
    - run: |
        gh auth status || true
        git config --list
      shell: bash
      continue-on-error: true
    - run: |
        date > baz.txt
        git add baz.txt
        git commit -m "baz"
        git show
      shell: bash
      continue-on-error: true
