name: 📦 Archive Lint reports
description: Archive Lint reports
inputs:
  analysis:
    description: A SARIF file to run CodeQL analysis on
  html:
    description: A file, directory or wildcard pattern that describes what to upload
  sarif:
    description: A file, directory or wildcard pattern that describes what to upload
  xml:
    description: A file, directory or wildcard pattern that describes what to upload
runs:
  using: composite
  steps:
    - name: Archive Lint HTML reports
      if: inputs.html != ''
      uses: actions/upload-artifact@v4
      with:
        name: lint-html
        path: ${{ inputs.html }}
        if-no-files-found: ignore
    - name: Archive Lint XML reports
      if: inputs.xml != ''
      uses: actions/upload-artifact@v4
      with:
        name: lint-xml
        path: ${{ inputs.xml }}
        if-no-files-found: ignore
    - name: Archive Lint SARIF reports
      if: inputs.sarif != ''
      uses: actions/upload-artifact@v4
      with:
        name: lint-sarif
        path: ${{ inputs.sarif }}
        if-no-files-found: ignore
    - name: Analyse Lint SARIF report
      if: inputs.analysis != ''
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.analysis }}
        category: android-lint
