# Based on https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#force-deleting-cache-entries
name: ♻️ Clear GitHub Actions cache

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  contents: read

env:
  GH_TOKEN: ${{ github.token }}
  GH_REPO: ${{ github.repository }}

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - run: gh cache list --limit 50 | sed -e 's/\x1b\[[0-9;]*m//g' >> $GITHUB_STEP_SUMMARY
      - name: Clear all cache entries
        if: github.event_name == 'workflow_dispatch'
        run: |
          set +e
          gh cache delete --all | sed -e 's/\x1b\[[0-9;]*m//g' >> $GITHUB_STEP_SUMMARY
      - name: Clear cache entries from PR
        if: github.event_name == 'pull_request'
        run: |
          set +e
          refs=("refs/pull/17/head" "refs/pull/17/merge")
          for ref in "${refs[@]}"; do
            for key in $(gh cache list --ref "$ref" --limit 100 --json id --jq 'map(.id) | join("\n")'); do
              gh cache delete "$key" | sed -e 's/\x1b\[[0-9;]*m//g' >> $GITHUB_STEP_SUMMARY
            done
          done
        with:
          PR: ${{ github.event.pull_request.number }}
