name: 🤖 Dependabot Gradle dependencies
on:
  pull_request:
    paths:
      - '**.gradle.kts'
      - '**/*.versions.toml'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  dependabot-gradle-dependencies:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && startsWith(github.head_ref, 'dependabot/gradle/')
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - id: get-user-id
        run: echo "user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name "${APP_SLUG}[bot]"
          git config --global user.email "${APP_USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          APP_USER_ID: ${{ steps.get-user-id.outputs.user-id }}
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-gradle
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - uses: ./.github/actions/setup-gradle-properties

      - id: gradle-signature-verification
        run: |
          ./gradlew --write-verification-metadata pgp,sha256 --export-keys
          
          # Remove unnecessary version attributes from trusted-key entries
          sed -i 's/<trusted-key\(.*\) version="[^"]*"/<trusted-key\1/g' gradle/verification-metadata.xml

          if ! git diff --quiet --exit-code -- 'gradle/verification-keyring.keys' 'gradle/verification-metadata.xml';
          then
            git commit -m "🤖 Update Gradle dependency signatures" -m "[dependabot skip]" -- 'gradle/verification-keyring.keys' 'gradle/verification-metadata.xml'
            git show

            echo "::notice::UPDATED"
            echo "dirty=true" >> $GITHUB_OUTPUT
          else
            echo "::notice::UP-TO-DATE"
          fi

      - name: Disable auto-merge for this PR
        if: steps.gradle-signature-verification.outputs.dirty == 'true'
        run: gh pr merge --disable-auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}

      - id: gradle-dependency-guard-baseline
        run: |
          ./gradlew dependencyGuardBaseline

          if ! git diff --quiet --exit-code -- ':(glob)**/dependencies/*.txt';
          then
            git commit -m "🤖 Update Dependency Guard baseline" -m "[dependabot skip]" -- ':(glob)**/dependencies/*.txt'
            git show

            echo "::notice::UPDATED"
            echo "dirty=true" >> $GITHUB_OUTPUT
          else
            echo "::notice::UP-TO-DATE"
          fi

      - name: Update the PR with new commits
        if: ${{ !cancelled() && contains(steps.*.outputs.dirty, 'true') }}
        run: git push
