name: 📸 Paparazzi Golden Images

on:
  workflow_dispatch:
    inputs:
      ref:
        description: PR number, branch, or url
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  paparazzi-golden-images:
    if: github.actor == 'SimonMarquis'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - id: get-user-id
        run: echo "user-id=$(gh api "/users/${APP_SLUG}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - uses: actions/checkout@v4
        with:
          lfs: true
          token: ${{ steps.app-token.outputs.token }}
      - if: inputs.ref != ''
        run: gh pr checkout "$INPUT_REF"
        env:
          INPUT_REF: ${{ inputs.ref }}
          token: ${{ steps.app-token.outputs.token }}
      - run: |
          git config --global user.name "${APP_SLUG}[bot]"
          git config --global user.email "${APP_USER_ID}+${APP_SLUG}[bot]@users.noreply.github.com"
        env:
          APP_SLUG: ${{ steps.app-token.outputs.app-slug }}
          APP_USER_ID: ${{ steps.get-user-id.outputs.user-id }}

      - uses: ./.github/actions/check-git-lfs
      - uses: ./.github/actions/setup-java
      - uses: ./.github/actions/setup-gradle
      - uses: ./.github/actions/setup-gradle-properties
      - run: ./gradlew cleanRecordScreenshots
      - run: |
          git status --porcelain
          git add -- '**/src/test/snapshots/**/*.png'
  
          if ! git diff --cached --quiet --exit-code -- '**/src/test/snapshots/**/*.png' ; then
            git commit -m "📸 Update Paparazzi golden images" -- '**/src/test/snapshots/**/*.png'
            git show
  
            if [[ -z "${INPUT_REF}" ]]; then
              new_pr_branch="paparazzi/$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER"
              git switch --create "$new_pr_branch"
              git push origin "$new_pr_branch"
              gh pr create \
                --title "📸 Update Paparazzi golden images" --fill \
                --base "$GITHUB_REF_NAME" --head "$new_pr_branch" \
                --assignee "$GITHUB_TRIGGERING_ACTOR"
            else
              git push
            fi
            echo "::notice::UPDATED"
          else
            echo "::notice::UP-TO-DATE"
          fi
        env:
          INPUT_REF: ${{ inputs.ref }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}